### ISSUE TITLE
我想问一下，您在开发过程使用中关于 cherry-markdown的setMarkdown等插入文本的方法是否会出现一些问题

### ISSUE THREAD

**Issue by stonexwx** [RSS1102/electron-markdown-notepad#2]
https://github.com/Tencent/cherry-markdown/issues/383
https://github.com/Tencent/cherry-markdown/issues/381
我在使用中会出现上面两种奇怪的bug
不知道您是否遇到过
如果遇到过能告诉我一下如何解决吗

**Comment by stonexwx** [comment]
破案了，new Cherry返回的对象不能被代理，vue3的ref会导致Cherry的方法产生奇奇怪怪的bug

**Comment by RSS1102** [comment]
> 

你使用id的方式呢？一般不会出现这个问题的啊。你有最小demo看下面嘛？
最近比较忙，这个目前搁置了一段时间。

**Comment by stonexwx** [comment]
新年快乐！我设置了个单例，保证只初始化一个Cherry对象就解决了，引起异常的原因我看起来应该是Cherry不能被代理

**Comment by RSS1102** [comment]
> 新年快乐！我设置了个单例，保证只初始化一个Cherry对象就解决了，引起异常的原因我看起来应该是Cherry不能被代理

新年快乐。
那可以只要找到原因就好处理了。
